version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      # orb's defalt or any from https://hub.docker.com/r/cimg/node/tags
      name: node/default 
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            # Move below command to "test-ci" script
            - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
workflows:
    build-and-test:
      jobs:
        - build-and-test